/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTopicsRouteImport } from './routes/_app.topics'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRevisionsRouteImport } from './routes/_app.revisions'
import { Route as AppProblemsRouteImport } from './routes/_app.problems'
import { Route as AppPatternsRouteImport } from './routes/_app.patterns'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppTopicsIndexRouteImport } from './routes/_app.topics.index'
import { Route as AppProblemsIndexRouteImport } from './routes/_app.problems.index'
import { Route as AppPatternsIndexRouteImport } from './routes/_app.patterns.index'
import { Route as AppTopicsTopicRouteImport } from './routes/_app.topics.$topic'
import { Route as AppProblemsNewRouteImport } from './routes/_app.problems.new'
import { Route as AppProblemsIdRouteImport } from './routes/_app.problems.$id'
import { Route as AppPracticeIdRouteImport } from './routes/_app.practice.$id'
import { Route as AppPatternsPatternRouteImport } from './routes/_app.patterns.$pattern'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopicsRoute = AppTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionsRoute = AppRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AppRoute,
} as any)
const AppProblemsRoute = AppProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AppRoute,
} as any)
const AppPatternsRoute = AppPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsIndexRoute = AppTopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTopicsRoute,
} as any)
const AppProblemsIndexRoute = AppProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProblemsRoute,
} as any)
const AppPatternsIndexRoute = AppPatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPatternsRoute,
} as any)
const AppTopicsTopicRoute = AppTopicsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => AppTopicsRoute,
} as any)
const AppProblemsNewRoute = AppProblemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProblemsRoute,
} as any)
const AppProblemsIdRoute = AppProblemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProblemsRoute,
} as any)
const AppPracticeIdRoute = AppPracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPatternsPatternRoute = AppPatternsPatternRouteImport.update({
  id: '/$pattern',
  path: '/$pattern',
  getParentRoute: () => AppPatternsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/home': typeof AppHomeRoute
  '/patterns': typeof AppPatternsRouteWithChildren
  '/problems': typeof AppProblemsRouteWithChildren
  '/revisions': typeof AppRevisionsRoute
  '/settings': typeof AppSettingsRoute
  '/topics': typeof AppTopicsRouteWithChildren
  '/patterns/$pattern': typeof AppPatternsPatternRoute
  '/practice/$id': typeof AppPracticeIdRoute
  '/problems/$id': typeof AppProblemsIdRoute
  '/problems/new': typeof AppProblemsNewRoute
  '/topics/$topic': typeof AppTopicsTopicRoute
  '/patterns/': typeof AppPatternsIndexRoute
  '/problems/': typeof AppProblemsIndexRoute
  '/topics/': typeof AppTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/home': typeof AppHomeRoute
  '/revisions': typeof AppRevisionsRoute
  '/settings': typeof AppSettingsRoute
  '/patterns/$pattern': typeof AppPatternsPatternRoute
  '/practice/$id': typeof AppPracticeIdRoute
  '/problems/$id': typeof AppProblemsIdRoute
  '/problems/new': typeof AppProblemsNewRoute
  '/topics/$topic': typeof AppTopicsTopicRoute
  '/patterns': typeof AppPatternsIndexRoute
  '/problems': typeof AppProblemsIndexRoute
  '/topics': typeof AppTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/patterns': typeof AppPatternsRouteWithChildren
  '/_app/problems': typeof AppProblemsRouteWithChildren
  '/_app/revisions': typeof AppRevisionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/topics': typeof AppTopicsRouteWithChildren
  '/_app/patterns/$pattern': typeof AppPatternsPatternRoute
  '/_app/practice/$id': typeof AppPracticeIdRoute
  '/_app/problems/$id': typeof AppProblemsIdRoute
  '/_app/problems/new': typeof AppProblemsNewRoute
  '/_app/topics/$topic': typeof AppTopicsTopicRoute
  '/_app/patterns/': typeof AppPatternsIndexRoute
  '/_app/problems/': typeof AppProblemsIndexRoute
  '/_app/topics/': typeof AppTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/home'
    | '/patterns'
    | '/problems'
    | '/revisions'
    | '/settings'
    | '/topics'
    | '/patterns/$pattern'
    | '/practice/$id'
    | '/problems/$id'
    | '/problems/new'
    | '/topics/$topic'
    | '/patterns/'
    | '/problems/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/home'
    | '/revisions'
    | '/settings'
    | '/patterns/$pattern'
    | '/practice/$id'
    | '/problems/$id'
    | '/problems/new'
    | '/topics/$topic'
    | '/patterns'
    | '/problems'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/home'
    | '/_app/patterns'
    | '/_app/problems'
    | '/_app/revisions'
    | '/_app/settings'
    | '/_app/topics'
    | '/_app/patterns/$pattern'
    | '/_app/practice/$id'
    | '/_app/problems/$id'
    | '/_app/problems/new'
    | '/_app/topics/$topic'
    | '/_app/patterns/'
    | '/_app/problems/'
    | '/_app/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/topics': {
      id: '/_app/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AppTopicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revisions': {
      id: '/_app/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof AppRevisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/problems': {
      id: '/_app/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AppProblemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patterns': {
      id: '/_app/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AppPatternsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topics/': {
      id: '/_app/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof AppTopicsIndexRouteImport
      parentRoute: typeof AppTopicsRoute
    }
    '/_app/problems/': {
      id: '/_app/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof AppProblemsIndexRouteImport
      parentRoute: typeof AppProblemsRoute
    }
    '/_app/patterns/': {
      id: '/_app/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof AppPatternsIndexRouteImport
      parentRoute: typeof AppPatternsRoute
    }
    '/_app/topics/$topic': {
      id: '/_app/topics/$topic'
      path: '/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof AppTopicsTopicRouteImport
      parentRoute: typeof AppTopicsRoute
    }
    '/_app/problems/new': {
      id: '/_app/problems/new'
      path: '/new'
      fullPath: '/problems/new'
      preLoaderRoute: typeof AppProblemsNewRouteImport
      parentRoute: typeof AppProblemsRoute
    }
    '/_app/problems/$id': {
      id: '/_app/problems/$id'
      path: '/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof AppProblemsIdRouteImport
      parentRoute: typeof AppProblemsRoute
    }
    '/_app/practice/$id': {
      id: '/_app/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof AppPracticeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patterns/$pattern': {
      id: '/_app/patterns/$pattern'
      path: '/$pattern'
      fullPath: '/patterns/$pattern'
      preLoaderRoute: typeof AppPatternsPatternRouteImport
      parentRoute: typeof AppPatternsRoute
    }
  }
}

interface AppPatternsRouteChildren {
  AppPatternsPatternRoute: typeof AppPatternsPatternRoute
  AppPatternsIndexRoute: typeof AppPatternsIndexRoute
}

const AppPatternsRouteChildren: AppPatternsRouteChildren = {
  AppPatternsPatternRoute: AppPatternsPatternRoute,
  AppPatternsIndexRoute: AppPatternsIndexRoute,
}

const AppPatternsRouteWithChildren = AppPatternsRoute._addFileChildren(
  AppPatternsRouteChildren,
)

interface AppProblemsRouteChildren {
  AppProblemsIdRoute: typeof AppProblemsIdRoute
  AppProblemsNewRoute: typeof AppProblemsNewRoute
  AppProblemsIndexRoute: typeof AppProblemsIndexRoute
}

const AppProblemsRouteChildren: AppProblemsRouteChildren = {
  AppProblemsIdRoute: AppProblemsIdRoute,
  AppProblemsNewRoute: AppProblemsNewRoute,
  AppProblemsIndexRoute: AppProblemsIndexRoute,
}

const AppProblemsRouteWithChildren = AppProblemsRoute._addFileChildren(
  AppProblemsRouteChildren,
)

interface AppTopicsRouteChildren {
  AppTopicsTopicRoute: typeof AppTopicsTopicRoute
  AppTopicsIndexRoute: typeof AppTopicsIndexRoute
}

const AppTopicsRouteChildren: AppTopicsRouteChildren = {
  AppTopicsTopicRoute: AppTopicsTopicRoute,
  AppTopicsIndexRoute: AppTopicsIndexRoute,
}

const AppTopicsRouteWithChildren = AppTopicsRoute._addFileChildren(
  AppTopicsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPatternsRoute: typeof AppPatternsRouteWithChildren
  AppProblemsRoute: typeof AppProblemsRouteWithChildren
  AppRevisionsRoute: typeof AppRevisionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTopicsRoute: typeof AppTopicsRouteWithChildren
  AppPracticeIdRoute: typeof AppPracticeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHomeRoute: AppHomeRoute,
  AppPatternsRoute: AppPatternsRouteWithChildren,
  AppProblemsRoute: AppProblemsRouteWithChildren,
  AppRevisionsRoute: AppRevisionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTopicsRoute: AppTopicsRouteWithChildren,
  AppPracticeIdRoute: AppPracticeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
